// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	statsd "github.com/DataDog/datadog-go/v5/statsd"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// StatsdInterface is an autogenerated mock type for the statsdInterface type
type StatsdInterface struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *StatsdInterface) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Count provides a mock function with given fields: name, value, tags, rate
func (_m *StatsdInterface) Count(name string, value int64, tags []string, rate float64) error {
	ret := _m.Called(name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64, []string, float64) error); ok {
		r0 = rf(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountWithTimestamp provides a mock function with given fields: name, value, tags, rate, timestamp
func (_m *StatsdInterface) CountWithTimestamp(name string, value int64, tags []string, rate float64, timestamp time.Time) error {
	ret := _m.Called(name, value, tags, rate, timestamp)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int64, []string, float64, time.Time) error); ok {
		r0 = rf(name, value, tags, rate, timestamp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Decr provides a mock function with given fields: name, tags, rate
func (_m *StatsdInterface) Decr(name string, tags []string, rate float64) error {
	ret := _m.Called(name, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string, float64) error); ok {
		r0 = rf(name, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Distribution provides a mock function with given fields: name, value, tags, rate
func (_m *StatsdInterface) Distribution(name string, value float64, tags []string, rate float64) error {
	ret := _m.Called(name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, []string, float64) error); ok {
		r0 = rf(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Event provides a mock function with given fields: e
func (_m *StatsdInterface) Event(e *statsd.Event) error {
	ret := _m.Called(e)

	var r0 error
	if rf, ok := ret.Get(0).(func(*statsd.Event) error); ok {
		r0 = rf(e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Flush provides a mock function with given fields:
func (_m *StatsdInterface) Flush() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Gauge provides a mock function with given fields: name, value, tags, rate
func (_m *StatsdInterface) Gauge(name string, value float64, tags []string, rate float64) error {
	ret := _m.Called(name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, []string, float64) error); ok {
		r0 = rf(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GaugeWithTimestamp provides a mock function with given fields: name, value, tags, rate, timestamp
func (_m *StatsdInterface) GaugeWithTimestamp(name string, value float64, tags []string, rate float64, timestamp time.Time) error {
	ret := _m.Called(name, value, tags, rate, timestamp)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, []string, float64, time.Time) error); ok {
		r0 = rf(name, value, tags, rate, timestamp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTelemetry provides a mock function with given fields:
func (_m *StatsdInterface) GetTelemetry() statsd.Telemetry {
	ret := _m.Called()

	var r0 statsd.Telemetry
	if rf, ok := ret.Get(0).(func() statsd.Telemetry); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(statsd.Telemetry)
	}

	return r0
}

// Histogram provides a mock function with given fields: name, value, tags, rate
func (_m *StatsdInterface) Histogram(name string, value float64, tags []string, rate float64) error {
	ret := _m.Called(name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, []string, float64) error); ok {
		r0 = rf(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Incr provides a mock function with given fields: name, tags, rate
func (_m *StatsdInterface) Incr(name string, tags []string, rate float64) error {
	ret := _m.Called(name, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []string, float64) error); ok {
		r0 = rf(name, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IsClosed provides a mock function with given fields:
func (_m *StatsdInterface) IsClosed() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ServiceCheck provides a mock function with given fields: sc
func (_m *StatsdInterface) ServiceCheck(sc *statsd.ServiceCheck) error {
	ret := _m.Called(sc)

	var r0 error
	if rf, ok := ret.Get(0).(func(*statsd.ServiceCheck) error); ok {
		r0 = rf(sc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Set provides a mock function with given fields: name, value, tags, rate
func (_m *StatsdInterface) Set(name string, value string, tags []string, rate float64) error {
	ret := _m.Called(name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []string, float64) error); ok {
		r0 = rf(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SimpleEvent provides a mock function with given fields: title, text
func (_m *StatsdInterface) SimpleEvent(title string, text string) error {
	ret := _m.Called(title, text)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(title, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SimpleServiceCheck provides a mock function with given fields: name, status
func (_m *StatsdInterface) SimpleServiceCheck(name string, status statsd.ServiceCheckStatus) error {
	ret := _m.Called(name, status)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, statsd.ServiceCheckStatus) error); ok {
		r0 = rf(name, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TimeInMilliseconds provides a mock function with given fields: name, value, tags, rate
func (_m *StatsdInterface) TimeInMilliseconds(name string, value float64, tags []string, rate float64) error {
	ret := _m.Called(name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, float64, []string, float64) error); ok {
		r0 = rf(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Timing provides a mock function with given fields: name, value, tags, rate
func (_m *StatsdInterface) Timing(name string, value time.Duration, tags []string, rate float64) error {
	ret := _m.Called(name, value, tags, rate)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Duration, []string, float64) error); ok {
		r0 = rf(name, value, tags, rate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewStatsdInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewStatsdInterface creates a new instance of StatsdInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStatsdInterface(t mockConstructorTestingTNewStatsdInterface) *StatsdInterface {
	mock := &StatsdInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
