// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for InvoiceStatusEnum.
const (
	DRAFT          InvoiceStatusEnum = "DRAFT"
	OVERDUE        InvoiceStatusEnum = "OVERDUE"
	PAID           InvoiceStatusEnum = "PAID"
	PENDINGPAYMENT InvoiceStatusEnum = "PENDING_PAYMENT"
)

// Defines values for UpdateInvoiceStatus.
const (
	Draft   UpdateInvoiceStatus = "draft"
	Overdue UpdateInvoiceStatus = "overdue"
	Paid    UpdateInvoiceStatus = "paid"
)

// Activity defines model for Activity.
type Activity struct {
	CreatedAt   *time.Time          `json:"createdAt,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	Type        *string             `json:"type,omitempty"`
}

// CustomerFilters defines model for CustomerFilters.
type CustomerFilters struct {
	UserId *[]string `json:"user_id,omitempty"`
}

// CustomerRequestBodyData defines model for CustomerRequestBodyData.
type CustomerRequestBodyData struct {
	Email *string `json:"email,omitempty"`
	Name  *string `json:"name,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

// CustomerResponseData defines model for CustomerResponseData.
type CustomerResponseData struct {
	Email string             `json:"email"`
	Id    openapi_types.UUID `json:"id"`
	Name  string             `json:"name"`
	Phone string             `json:"phone"`
}

// Error defines model for Error.
type Error struct {
	Code   string                  `json:"code"`
	Detail string                  `json:"detail"`
	Meta   *map[string]interface{} `json:"meta,omitempty"`
	Status int                     `json:"status"`
	Title  string                  `json:"title"`
}

// ErrorResponse Response that contains the list of errors
type ErrorResponse struct {
	Errors []Error `json:"errors"`
}

// InvoiceFilters defines model for InvoiceFilters.
type InvoiceFilters struct {
	CustomerId    *[]string            `json:"customer_id,omitempty"`
	Id            *[]string            `json:"id,omitempty"`
	InvoiceNumber *[]string            `json:"invoice_number,omitempty"`
	Status        *[]InvoiceStatusEnum `json:"status,omitempty"`
	UserId        *[]string            `json:"user_id,omitempty"`
}

// InvoiceRequestBodyData defines model for InvoiceRequestBodyData.
type InvoiceRequestBodyData struct {
	CustomerId *openapi_types.UUID `json:"customer_id,omitempty"`
	DueDate    *openapi_types.Date `json:"due_date,omitempty"`
	IssueDate  *openapi_types.Date `json:"issue_date,omitempty"`
	Items      []Item              `json:"items"`
	UserId     *openapi_types.UUID `json:"user_id,omitempty"`
}

// InvoiceResponseData defines model for InvoiceResponseData.
type InvoiceResponseData struct {
	Customer    string             `json:"customer"`
	DueDate     openapi_types.Date `json:"due_date"`
	Id          openapi_types.UUID `json:"id"`
	Items       []Item             `json:"items"`
	Sender      string             `json:"sender"`
	Status      InvoiceStatusEnum  `json:"status"`
	TotalAmount *float32           `json:"total_amount,omitempty"`
}

// InvoiceStatusEnum defines model for InvoiceStatusEnum.
type InvoiceStatusEnum string

// Item defines model for Item.
type Item struct {
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`
	InvoiceId   *openapi_types.UUID `json:"invoice_id,omitempty"`
	Quantity    *int                `json:"quantity,omitempty"`
	TotalPrice  *float32            `json:"total_price,omitempty"`
	UnitPrice   *float32            `json:"unit_price,omitempty"`
}

// UpdateInvoice defines model for UpdateInvoice.
type UpdateInvoice struct {
	DueDate *openapi_types.Date  `json:"dueDate,omitempty"`
	Status  *UpdateInvoiceStatus `json:"status,omitempty"`
}

// UpdateInvoiceStatus defines model for UpdateInvoice.Status.
type UpdateInvoiceStatus string

// CustomerResponse defines model for CustomerResponse.
type CustomerResponse struct {
	Data CustomerResponseData `json:"data"`
}

// CustomersResponse defines model for CustomersResponse.
type CustomersResponse struct {
	Data []CustomerResponseData `json:"data"`
}

// InvoiceResponse defines model for InvoiceResponse.
type InvoiceResponse struct {
	Data InvoiceResponseData `json:"data"`
}

// InvoicesResponse defines model for InvoicesResponse.
type InvoicesResponse struct {
	Data []InvoiceResponseData `json:"data"`
}

// CreateCustomerRequestBody defines model for CreateCustomerRequestBody.
type CreateCustomerRequestBody struct {
	Data CustomerRequestBodyData `json:"data"`
}

// CreateInvoiceRequestBody defines model for CreateInvoiceRequestBody.
type CreateInvoiceRequestBody struct {
	Data InvoiceRequestBodyData `json:"data"`
}

// V1GetCustomersParams defines parameters for V1GetCustomers.
type V1GetCustomersParams struct {
	Data *struct {
		Filters *CustomerFilters `json:"filters,omitempty"`
	} `json:"data,omitempty"`
}

// V1CreateCustomerJSONBody defines parameters for V1CreateCustomer.
type V1CreateCustomerJSONBody struct {
	Data CustomerRequestBodyData `json:"data"`
}

// V1GetInvoicesParams defines parameters for V1GetInvoices.
type V1GetInvoicesParams struct {
	// Data Filter invoices by status (paid, overdue, draft, etc.)
	Data *struct {
		Filters *InvoiceFilters `json:"filters,omitempty"`

		// Page The page number
		Page *int `json:"page,omitempty"`

		// PageSize The page size
		PageSize *int `json:"page_size,omitempty"`
	} `json:"data,omitempty"`
}

// V1CreateInvoiceJSONBody defines parameters for V1CreateInvoice.
type V1CreateInvoiceJSONBody struct {
	Data InvoiceRequestBodyData `json:"data"`
}

// V1CreateCustomerJSONRequestBody defines body for V1CreateCustomer for application/json ContentType.
type V1CreateCustomerJSONRequestBody V1CreateCustomerJSONBody

// V1CreateInvoiceJSONRequestBody defines body for V1CreateInvoice for application/json ContentType.
type V1CreateInvoiceJSONRequestBody V1CreateInvoiceJSONBody

// V1UpdateInvoiceJSONRequestBody defines body for V1UpdateInvoice for application/json ContentType.
type V1UpdateInvoiceJSONRequestBody = UpdateInvoice

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get recent activities
	// (GET /v1/activities)
	V1GetActivities(w http.ResponseWriter, r *http.Request)
	// List all customers
	// (GET /v1/customers)
	V1GetCustomers(w http.ResponseWriter, r *http.Request, params V1GetCustomersParams)
	// Create a new customer
	// (POST /v1/customers)
	V1CreateCustomer(w http.ResponseWriter, r *http.Request)
	// List all invoices
	// (GET /v1/invoices)
	V1GetInvoices(w http.ResponseWriter, r *http.Request, params V1GetInvoicesParams)
	// Create a new invoice
	// (POST /v1/invoices)
	V1CreateInvoice(w http.ResponseWriter, r *http.Request)
	// Delete an invoice
	// (DELETE /v1/invoices/{invoiceId})
	V1DeleteInvoice(w http.ResponseWriter, r *http.Request, invoiceId string)
	// Get details of a specific invoice
	// (GET /v1/invoices/{invoiceId})
	V1GetInvoice(w http.ResponseWriter, r *http.Request, invoiceId openapi_types.UUID)
	// Update an invoice
	// (PATCH /v1/invoices/{invoiceId})
	V1UpdateInvoice(w http.ResponseWriter, r *http.Request, invoiceId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get recent activities
// (GET /v1/activities)
func (_ Unimplemented) V1GetActivities(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all customers
// (GET /v1/customers)
func (_ Unimplemented) V1GetCustomers(w http.ResponseWriter, r *http.Request, params V1GetCustomersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new customer
// (POST /v1/customers)
func (_ Unimplemented) V1CreateCustomer(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all invoices
// (GET /v1/invoices)
func (_ Unimplemented) V1GetInvoices(w http.ResponseWriter, r *http.Request, params V1GetInvoicesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new invoice
// (POST /v1/invoices)
func (_ Unimplemented) V1CreateInvoice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete an invoice
// (DELETE /v1/invoices/{invoiceId})
func (_ Unimplemented) V1DeleteInvoice(w http.ResponseWriter, r *http.Request, invoiceId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get details of a specific invoice
// (GET /v1/invoices/{invoiceId})
func (_ Unimplemented) V1GetInvoice(w http.ResponseWriter, r *http.Request, invoiceId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an invoice
// (PATCH /v1/invoices/{invoiceId})
func (_ Unimplemented) V1UpdateInvoice(w http.ResponseWriter, r *http.Request, invoiceId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// V1GetActivities operation middleware
func (siw *ServerInterfaceWrapper) V1GetActivities(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetActivities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetCustomers operation middleware
func (siw *ServerInterfaceWrapper) V1GetCustomers(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetCustomersParams

	// ------------- Optional query parameter "data" -------------

	err = runtime.BindQueryParameter("deepObject", true, false, "data", r.URL.Query(), &params.Data)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "data", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetCustomers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1CreateCustomer operation middleware
func (siw *ServerInterfaceWrapper) V1CreateCustomer(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1CreateCustomer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetInvoices operation middleware
func (siw *ServerInterfaceWrapper) V1GetInvoices(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params V1GetInvoicesParams

	// ------------- Optional query parameter "data" -------------

	err = runtime.BindQueryParameter("deepObject", true, false, "data", r.URL.Query(), &params.Data)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "data", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetInvoices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1CreateInvoice operation middleware
func (siw *ServerInterfaceWrapper) V1CreateInvoice(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1CreateInvoice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1DeleteInvoice operation middleware
func (siw *ServerInterfaceWrapper) V1DeleteInvoice(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "invoiceId" -------------
	var invoiceId string

	err = runtime.BindStyledParameterWithOptions("simple", "invoiceId", chi.URLParam(r, "invoiceId"), &invoiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invoiceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1DeleteInvoice(w, r, invoiceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1GetInvoice operation middleware
func (siw *ServerInterfaceWrapper) V1GetInvoice(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "invoiceId" -------------
	var invoiceId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "invoiceId", chi.URLParam(r, "invoiceId"), &invoiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invoiceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1GetInvoice(w, r, invoiceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// V1UpdateInvoice operation middleware
func (siw *ServerInterfaceWrapper) V1UpdateInvoice(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "invoiceId" -------------
	var invoiceId string

	err = runtime.BindStyledParameterWithOptions("simple", "invoiceId", chi.URLParam(r, "invoiceId"), &invoiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "invoiceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.V1UpdateInvoice(w, r, invoiceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/activities", wrapper.V1GetActivities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/customers", wrapper.V1GetCustomers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/customers", wrapper.V1CreateCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/invoices", wrapper.V1GetInvoices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/invoices", wrapper.V1CreateInvoice)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/invoices/{invoiceId}", wrapper.V1DeleteInvoice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/invoices/{invoiceId}", wrapper.V1GetInvoice)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/invoices/{invoiceId}", wrapper.V1UpdateInvoice)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa2W/juBn/Vwi2Dy0gx0eSycRP9W6yAwPdTDDHAsXAMBjpk82tRGpIyl030P9e8NBN",
	"X5lsmoc8bZYiv/P3nZ5HHPI04wyYknj6iAV8z0Gqn3hEwRz8LIAo+DmXiqcgPlWft/pjyJkCpvSfJMsS",
	"GhJFORv+LjnTZzJcQ0r0X5ngGQjlaEZEmdO/CojxFP9lWMswtG/k0MPxRj8risAISQVEePrN0loEWG0z",
	"wFPMH36HUOFCX4tAhoJmWiQ8dYqgki5yhJHRpQjc9znbcBrCy+nZZ/gsajqyHS0NUZlxJp1zKyPbwxfz",
	"qWX3Y5rCHyTNEkClRsaJjoN8Ro2oglQ+TbVKCyIE2T5d1bBUq6VsBZ0XcV6H24/57tbjO8fgxV3nVey5",
	"PNdXtAic2EawWajohqptX4fQBHI0M8rHXKRE4almDANFU8AVc6kEZSvcZf3Y/06jFq08p5GPjD3ovS96",
	"6tbx9gtNFAjZ1yKXIJaWb+WMHQwbpt7Jp5sme/wgJTTxMmEkBe+HbM3Zqfq2wHKCEEd64CmyNuFpqBoi",
	"gROmfLrwKHUrBBceAPLIL0QEapd+KVh79HhIRVTe9D5lClYgjPupSo5Qyl6r2Fc0AytpT7MA/zFwNcIw",
	"LkNxXCuHJYgNiCUYC9Sa4c8gNrp8KkgzLoigyRbljGwITchDAgESoMQWJUSBfleqHZJcQrR82OpCnBAp",
	"77QPGupfjkaVvoYJCGSZm9xhPNHMf+1kUn5Bak0U0rmRUCaRWgNKqFSIx5aYtkkHkfb42JRoEXEoCTqi",
	"i1qjtvweqLlcuzNdlIWumzKcH7UoJHx/EZPR4DyE8eCCXD0M3p/H54MJRBfvzuMwGoXj3Umt1KSMxKcx",
	"uD6KgVV1yfL0AYSf2XhyfX5x+e7q/fURBOsQOqWsfTavblme+mj60vNJppgcNkWxGwcH03kHDwcTZ5TD",
	"UpfIXs30XaZSnnS9NNBx5ldwyOIHtOlEmwQWmWRT2gSXIhm1b7TUi32m3lexKprefH+SlY5z1PMY09nE",
	"J3QdLacHCVckWZKU56zdfMUJJ6rWxkW2t/ju81ZVtyrDljxnluceNzYk1aFq/vsN39/e3czvPizvZ//6",
	"9fbuCw7wx99uP918vcUBvvk0+0Wf3M/mN81c3SLoc5Exer+1fp4es8yOR17/nhOmXJvsaSCM8TJBQzjG",
	"XwHOGVXH3/clsK9ZVG8LPFZyAXlMxNRILd2ZEWMFvgER5ablESRuwmJ3i1oY28a8HJ5IqBodKQ7XRCQg",
	"w4QyxdlkNDr/x0p/Ogt52psg8Ox+jmIuUEoYWVG2Qs5rMkDVRBogwiJE7BhDQZ7hHsTQr/o9pMAUmt3P",
	"cYA3IKRlMT4bnY00Z54BIxnFU3xujgKcEbU2ZhluxsOagT5ZgdFKW9wMhPMIT/Fv4w+gZvW9zq5jMhqd",
	"NFEelZiq8a1f9frWrJo0AaG2RUMnMxXmaUqEbh0/gPLcCbAiK6nx0VByoV9qA1UO2W+fakFiDCxICrYR",
	"+/aIqRbyew5iWw4PUzvnBjvn7Lju445ZjpRtnzeipNoa0EQA2Ud3uvD70Merujfs74CKAF+c6P2D3XFN",
	"vO/pn0hULt4M78nk5Xh/ZZngIUip5xR0a7NmEeDLlzTAnCkQjCTIjThunmiB/J86GEiS1KmkgfAapgs9",
	"9XLpxXN7N42DxvZ6uxsnjQX3cPd2u+hBb3w89N6Q95qR51bkBDH4D2r0Zz7wuexaFr5Gcm3zrdBc3Qx8",
	"6Xdef+1k3zY5mykrYuhhi2ybgP6mm4MAud4gQKY1CBCo8Ozvusf805J4Z3TXYUlWbkkRkzxReDrueuPL",
	"GpC+hVwrFeCUMprqLmcceBo5fXcp6X/bZCeXO+mau/up/qm1prezfgv411xqGsFZBnt11Cw0nR0+izJO",
	"mUKKI7uVLwl5grz1M+LTS5Lnd8gnVaTub0Rv+HztBamGlgeinXI0fHR/zaPC4jYBO3V2YXljvtSw3Ft9",
	"5jd6SlHrJs5NYdEjWV1XKt64uQBRIodmsemOrP08e9EPuXJytApFSOahdmScJ8n2DcOvEcMWYIiw/QAO",
	"/O2TnnjdLd3rGOhFe1uoF8VwvRKPIvJw9S6+GsTXV9eDCzKOB9dX5P3ganx1SYCE1+8mmtSh1e6PNBtv",
	"ufw1x4FGsv0ZUWoAEiQzCGlMw0NxkREVrn2pu71q/L+n7qf9w6h9dm8rWLT36Vqmwh8t/pKRG2pvJeP1",
	"h4r1+8GSYR4ZKj7A3wse5aH+H2Qv4QDnIsFTvFYqk9PhkGT0zJEjWeY23V0yn5XdcO+gIe3nMx+tRSV1",
	"l+jHMpIlEpAYVCreHELa0Sg9ctnVebWlQG6Wdw/rTUX/5RdBwn9XRbW1R3avG2vkYlH8LwAA//+Kup3f",
	"CioAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
